name: baselines.trm_nocarry@TinyRecursiveModel
head: lm_head@LMHead

half_layers: True  # To match FLOPs and recurrence, layers need to be halved.

# TRM config
# Reduced L_cycles to match FLOPs
H_cycles: 2
L_cycles: 3

H_bp_steps: 2
L_bp_steps: 3
